### ISSUE TITLE
How to add tax to every item?

### ISSUE THREAD

**Issue by lakshyapunhani** [Invoiced/invoice-generator-api#22]
Right now what I can see is that I can make tax rate on the subtotal of all the items but what I want is to put tax on each item in item row because a vendor can sell items with different tax slabs but here he had to add just one tax on all the items? Please help

**Comment by jaredtking** [comment]
Unfortunately tax rates can only be applied at the invoice level with this API. If you wish to apply tax to each line item then you need to perform the calculation yourself and add it as a flat tax amount to the invoice. If you'd like you can even mention in the description of each line item the tax rate that was applied. Otherwise this is not a feature we plan on adding. Thank you for the feedback!
