### ISSUE TITLE
Python3 demo project 

### ISSUE THREAD

**Issue by amaanabbasi** [Invoiced/invoice-generator-api#35]
I think a Python demo project would be helpful for python developers.
 I'm willing to contribute a sample project using python.

**Comment by aleaforny** [comment]
I've created a ready-to-use InvoiceGenerator library so that it could be easy to use for Python developer. 
I'm using it for my projects, so I have not widely tested the library with the API, but I'm happy to share and get feedback as well as it can be improved!

Here the repo: https://github.com/aleaforny/python-invoice-generator

Basically, it's pretty simple to create an `Invoice` object, and download it. If you just want to do something else with the PDF (such as download it via browser directly), you can directly play with `response.content`

Let me know if I can help further!

**Comment by jaredtking** [comment]
This is awesome! I'll add it to the README. Thank you for your contribution

**Comment by Ashi-s** [comment]
Is there any way I can change the "Balance Due" in the invoice to "Balance Paid"
![GitHub Logo](/images/logo.png)

**Comment by Ashi-s** [comment]
Is there any way I can change the "Balance Due" in the invoice to "Balance Paid"
![Invoice image](https://drive.google.com/uc?export=view&id=1hXdQ5049x9MWHganADwTjCPHB_oPI0Y9)

**Comment by aleaforny** [comment]
I assume you can use `amount_paid_title `template parameter to set the text to **Balance Paid**, I'll let @jaredtking correct me if needed.

**Comment by Ashi-s** [comment]
Hi @aleaforny, Thanks for replying. I did update the constructor of the `InvoiceGenerator ` class & added `amount_paid_title `, but it didn't work for me.

I hope @jaredtking might have an answer for this.

Thanks again.

**Comment by jaredtking** [comment]
@aleaforny is right. You can use `amount_paid_title` and `balance_title` depending on which field you want to change. This is a complete list of all of the labels that you can change: https://github.com/Invoiced/invoice-generator-api#invoice-template

**Comment by aleaforny** [comment]
@Ashi-s sorry for my delayed feedback.

Actually, I've tested this on my hand:

```
from invoice_generator import InvoiceGenerator
invoice = InvoiceGenerator(sender="Invoiced, Inc", to="Parag", logo="https://invoiced.com/img/logo-invoice.png", number=1, notes="Thanks for your business!", shipping=50)
invoice.add_item(name="Starter Plan", quantity=1, unit_cost=99)
invoice.add_item(name="Fees", quantity=1, unit_cost="49")
invoice.set_template_text("balance_title", "Montant payé")
invoice.download("/tmp/test.pdf")
```

It works as expected:
![it works](https://i.ibb.co/gwG29y8/2020-12-15-22-24-38-Window.png)

C/C this code and it you should see that it works. 
If not, open an issue directly on repo https://github.com/aleaforny/python-invoice-generator with the error you get.
